### ISSUE TITLE
Error when receiving paidMediaPurchased

### ISSUE THREAD

**Issue by injektion** [vjik/telegram-bot-api#121]
Error when receiving Vjik\TelegramBot\Api\Type\Payment\PaidMediaPurchased with a payload

development.ERROR: Not found key "paid_media_payload" in result object. {"exception":"[object] (Vjik\\TelegramBot\\Api\\ParseResult\\NotFoundKeyInResultException(code: 0): Not found key \"paid_media_payload\" in result object.

{
    "update_id": 1585xxxxx,
    "purchased_paid_media": {
        "from": {
            "id": 13136xxxxx,
            "is_bot": false,
            "first_name": "X",
            "last_name": "X",
            "username": "xxxxxxxxxx",
            "language_code": "en"
        },
        "payload": "12345"
    }
}

**Comment by vjik** [comment]
Is docs non-actual?

https://core.telegram.org/bots/api#paidmediapurchased

Here field is called "paid_media_payload"...

**Comment by injektion** [comment]
Seems incorrect.   That json above is a raw request capture… is just “payload” outside of the purchased_paid_media object.  

The PR I submitted fixes it.

**Comment by vjik** [comment]
Done by #122

**Comment by vjik** [comment]
@injektion Thanks for issue! Version 0.4.4 with your fix is released.
